[workspace]
members = [
        "common",
        "solana-client-gen",
        "safe/cli",
        "safe/client",
        "safe/program/interface",
]
exclude = [
        "dex",
        "crank",
        "safe/program",
]